### ISSUE TITLE
Brick daemon does not compile

### ISSUE THREAD

**Issue by barutzinkow** [Tinkerforge/brickd#10]
When trying to run make for the brick daemon, I am getting the following error multiple times:

```
client.h:84:19: error: ‘IO’ has no member named ‘handle’
  (int)(client)->io->handle, client_get_authentication_state_name((client)->authentication_state)
                   ^
../daemonlib/log.h:95:76: note: in definition of macro ‘log_message_checked’
      log_message(level, &_log_source, debug_group, __FUNCTION__, __LINE__, __VA_ARGS__); \
```

I am using Ubuntu-based elementary OS Freya (0.3.2) with GCC 4.8.4, but since client.c does not even compile I appears to me as if there were some problem with the code. I have installed all the dependencies as listed in the README file, and cloned the daemonlib successfully, too.

**Comment by photron** [comment]
I think you're using mismatching versions of brickd and daemonlib.

It looks to me that you're trying to compiled brickd v2.3.0 with the current git version of daemonlib. That'll not work. You need to use matching version. The README was not clear about this. I've fixed that.

If you want to compile brickd v2.3.0 then you also need to use daemonlib for brickd-2.3.0, not the current git version.

**Comment by barutzinkow** [comment]
Thank you, now it works!
Am 22.06.17, 10:35, Matthias Bolte <notifications@github.com> schrieb:
I think you're using mismatching versions of brickd and daemonlib.
It looks to me that you're trying to compiled brickd v2.3.0 with the current git version of daemonlib. That'll not work. You need to use matching version. The README was not clear about this. I've fixed that.
If you want to compile brickd v2.3.0 then you also need to use daemonlib for brickd-2.3.0, not the current git version.
