### ISSUE TITLE
add brickd.service file for systemd

### ISSUE THREAD

**Issue by Niklatz** [Tinkerforge/brickd#11]
Currently the `brickd` daemon is started via the old init system `init.d`. Since most distributions moved over to `systemd` it might make sense to provide a `brickd.service` file for users. As it stands right now users of ubuntu can not follow the official linux documentation to start the `brickd` daemon.

[Official Linux installation documentation](https://www.tinkerforge.com/en/doc/Software/Brickd_Install_Linux.html#brickd-install-linux)

Installation via `.deb`package works (though I would prefer using the package manager for this so I also get updates).
I am able to run the `brickd` daemon by hand:

    $ brickd --version
    2.3.1

But trying to run it via the included `init.d` script fails:

    $ sudo /etc/init.d/brickd start
    [....] Starting brickd (via systemctl): brickd.serviceFailed to start brickd.service: Unit brickd.service not found.
     failed!

As hinted here the system expects a `brickd.service` file to exist but can't find it. [This seems to be the case for all versions of Ubuntu since 16.04, since a compatibility layer is used](https://askubuntu.com/a/893928)

#### System information

Up to date Ubuntu 16.04.4

#### Workaround

The simplest way to work around this I found so far is to simply start the daemon by hand when I want to use it:

    sudo brickd --daemon

I will see if I can come up with a working `.service` file when I find the time and comment here if I am successful.

**Comment by Niklatz** [comment]
Okay it really is as easy as I had hoped. Here are the contents of a working `brickd.service` file. The daemon can be started via `systemctl start brickd.service`.

    [Unit]
    Description=Start the brickd daemon for Tinkerforge bricks
    
    [Service]
    User=root
    ExecStart=/usr/bin/brickd --daemon
    
    [Install]
    WantedBy=multi-user.target

Do you have any hint where in the repo I would have to put the file for it to be installed correctly? I am more than happy to fork and submit a pull request. :smiley: 
My guess would be something like `src/build_data/linux/installer/lib/systemd/system/`?

**Comment by photron** [comment]
Okay, I'm done with the systemd integration. Maybe you could test the current git version.

**Comment by Niklatz** [comment]
Sorry I missed this today. I will try to check it next week when I am back at work where I have the bricks.

**Comment by Niklatz** [comment]
Seems to work as expected. Build and installation return no errors. `brickd` can be started via `systemctl` or `init.d` calls and the status is correctly shown with `systemctl status brickd.service`.
 :+1: 

__Unrelated side note:__ I noticed currently building with the `build_pkg.py` script only works with python2. For now on Ubuntu that is okay but end of life for python2 is approaching and I guess it would make sense to move the build script over to python3. If I find the time I will take a look at this but I believe/hope it shouldn't be too hard to make it compatible. Anyway, feel free to ignore this and close this issue.

**Comment by photron** [comment]
The script was meant to work with Python 3 already. Some bytes/str mismatches seemed to have crept in again. I've fixed that now.
