### ISSUE TITLE
Error controlling multiple stacks 

### ISSUE THREAD

**Issue by BehrendsAndre** [Tinkerforge/brickd#19]
When Controlling 7 stacks of silent stepper bricks via an USB hub, even switching on and off the LED of the bricks gets stuck.

In the log viewer the error I can see the following messages:

            event_winapi.c:184 Starting to poll on 78 USB event source(s)

            2020-07-07 14:32:42.738139 <W> <libusb:check_pollfds> too many HANDLEs to wait on

I traced it down a bit and it looks like libusb cant wait for more than 64 objects. 

I get the second message exactly 15 times, since the check for MAXIMUM_WAIT_OBJECTS is "==" this is consistent
with my guess.

However it looks like this has been "fixed" here:

https://github.com/libusb/libusb/commit/c730a8410c8fc683e845fefcc06d6ced349b583b#diff-f4788613f8416e2b052f5d0b145054b0

is it possible to recompile brickd, with the "new" libusb?

**Comment by photron** [comment]
Please test this brickd Version: https://download.tinkerforge.com/_stuff/brickd_windows_2_4_1_64fdfix.exe

**Comment by BehrendsAndre** [comment]
Wow, 

you were fast. And it works like a charm :D.

Thank you very much.
