### ISSUE TITLE
Windows Uninstaller may delete important user files

### ISSUE THREAD

**Issue by fvollmer** [Tinkerforge/brickd#22]
Hi,

my anti virus sandbox identified your uninstaller as potential malware, because it deleted all user files in the sandbox. After manual investigation it turns out there is an issue with your uninstaller. Your script runs (https://github.com/Tinkerforge/brickd/blob/master/src/build_data/windows/installer/brickd_installer.nsi.template#L177)

    RMDir /R "$INSTDIR"

This isn't best practice:
>Warning: using RMDir /r $INSTDIR in the uninstaller
>is not safe. Though it is unlikely, the user might select to install to
>the Program Files folder and so this command will wipe out the entire
>Program Files folder, including other programs that has nothing to do
>with the uninstaller. The user can also put other files but the
>program's files and would expect them to get deleted with the program.
>Solutions are [available](https://nsis.sourceforge.io/Uninstall_only_installed_files) for easily uninstalling only files which were installed by the installer.

https://nsis.sourceforge.io/Reference/RMDir

>The install directory ($INSTDIR) is saved in the registry after a successful install and then fetched again in the uninstaller. If not fetched from the registry manually (via a ReadRegStr) then it is set to $EXEDIR (the location of the uninstaller executable). This can be problematic, especially if a lazy NSIS script writer uses RMDir /r "$INSTDIR".
>
>What if $INSTDIR is empty because the registry key is missing? "$INSTDIR" will become "" which means that everything from the system root could be deleted INCLUDING THE OPERATING SYSTEM. This would also happen if the user ran the uninstaller from C:\ and if that uninstaller did not set $INSTDIR to anything. Also, what if the user has installed to his desktop, or perhaps to My Documents. Need I say more?
 
https://nsis.sourceforge.io/Validating_$INSTDIR_before_uninstall

In practice the uninstaller will most likely run fine, but fixing the issue sounds like a good idea anyway. Nice side effect would be that your uninstaller is less likely to be flagged by anti virus software.

**Comment by photron** [comment]
You are correct. We will address this issue. Thanks for reporting it.

**Comment by photron** [comment]
Fixed in commit 7dd025d901718691266c84da27188111d8f7f595
